# Generated by Django 3.2.10 on 2022-03-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurante')),
            ],
        ),
    ]
