# Generated by Django 3.2.10 on 2021-12-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('mesa', '0001_initial'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data', models.DateTimeField(auto_now=True)),
                ('session_key', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_pedido', models.TimeField(auto_now_add=True)),
                ('session_key', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False, null=True)),
                ('mesa_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa')),
                ('metodo_de_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.pagamento')),
                ('pedido', models.ManyToManyField(to='carrinho.Pedido')),
            ],
        ),
    ]
