# Generated by Django 3.2.10 on 2022-02-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
    ]
