# Generated by Django 3.2.10 on 2022-04-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('mesa', '0001_initial'),
        ('pagamento', '0002_auto_20220326_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.TextField()),
                ('codigo_conexao', models.IntegerField()),
                ('validado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoGarçom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
            ],
        ),
        migrations.CreateModel(
            name='CarrinhoGarçom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_pedido', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('mesa_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa')),
                ('metodo_de_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamento.metodosdepagamento')),
                ('pedidos', models.ManyToManyField(to='menu_garcom.PedidoGarçom')),
            ],
        ),
    ]
