# Generated by Django 3.2.10 on 2022-03-18 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_codigo_de_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo_de_convite',
            field=models.UUIDField(default=uuid.UUID('ea953c1c-f3f5-4f90-b1ec-aa9c117b8d93'), unique=True),
        ),
    ]
