# Generated by Django 3.2.10 on 2022-04-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True, default=None, null=True)),
                ('valor_unidade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerar_completo', models.BooleanField(default=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_cardapio_fisico.material')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_placa', models.CharField(max_length=50)),
                ('url_placa', models.URLField()),
                ('soliticatacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_cardapio_fisico.solicitacaocardapio')),
            ],
        ),
    ]
