# Generated by Django 3.2.10 on 2022-02-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='link_encurtado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
