# Generated by Django 3.2.10 on 2021-12-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=40, unique=True)),
                ('componentes', models.TextField(blank=True, default=None, null=True)),
                ('descricao', models.CharField(default=True, max_length=50, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='logo/logo_produtos/')),
                ('classificacao', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.item_classificacao')),
            ],
        ),
    ]
