# Generated by Django 3.2.10 on 2022-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='item_classificacao',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
