# Generated by Django 3.2.10 on 2021-12-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='item_classificacao',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
