# Generated by Django 3.2.10 on 2022-02-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220124_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classificacao', models.CharField(max_length=30, unique=True)),
                ('classificacao_img', models.ImageField(blank=True, default=None, null=True, upload_to='categorias/')),
            ],
        ),
        migrations.AlterField(
            model_name='item_classificacao',
            name='text',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='item_classificacao',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.classificacoes'),
        ),
    ]
