# Generated by Django 3.2.10 on 2022-02-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220202_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacoes',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelOptions(
            name='item_classificacao',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='item_classificacao',
            name='classificacao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.classificacoes'),
        ),
    ]
