# Generated by Django 3.2.10 on 2022-02-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220202_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacoes',
            name='classificacao_img',
        ),
        migrations.RemoveField(
            model_name='item',
            name='componentes',
        ),
    ]
